### PR TITLE
SummariseParser fix and test

### LINKED ISSUE #42: Add Junit testing for SummariseParser, allow for optional begin and end indices
Related to #38

### PR DESCRIPTION
**Pull request by JianJiaT**
Fixes #42

### CODE REVIEW

File: src/main/java/brokeculator/expense/ExpenseManager.java [hunk 1]
```diff
@@ -21,9 +21,13 @@ public void delete(int index) {
         expenses.remove(index);
     }
 
-    public double summariseExpenses() {
+    public double summariseExpenses(int beginIndex, int endIndex) {
         double total = 0;
-        for (Expense expense : expenses) {
+        if (endIndex == -1 || endIndex >= expenses.size()) {
+            endIndex = expenses.size() - 1;
```
Comment (mihirheda02) [inline src/main/java/brokeculator/expense/ExpenseManager.java:27]: This is a little nit picky but what if we did `endIndex = expenses.size()` so on line 29 we can do `ArrayList<Expense> expensesToList = new ArrayList<>(expenses.subList(beginIndex, endIndex));`

**Review by mihirheda02 — APPROVED** [review]
Everything looks good! Feel free to not make the change I mentioned. It was just a small nit pick.

File: src/main/java/brokeculator/expense/ExpenseManager.java (hunk 1 above)
Comment (JianJiaT) [reply src/main/java/brokeculator/expense/ExpenseManager.java:27]: We do `ArrayList<Expense> expensesToList = new ArrayList<>(expenses.subList(beginIndex, endIndex + 1));` on line 29 because we want endIndex to be inclusive, so I think we should keep this implementation
